name: Container Tests
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
      - 'release/v[0-9]+.x'  # e.g. release/v1.x
      - 'release/[a-z]+/v[0-9]+.x'  # e.g. release/ibctestnet/v1.x
      - 'release/v[0-9]+.[0-9]+.x'  # e.g. release/v0.0.x

jobs:
  container-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_REPO_READ_TOKEN }}
      - name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.19
      - name: Build images
        run: DOCKER_BUILDKIT=1 make test-container-build
      - name: Run container tests
        run: make test-container
